In [12]:
from datasets import load_dataset
import pandas as pd

dataset=load_dataset("SetFit/ag_news")
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 120000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 7600
    })
})

In [13]:
for i in range(5):
    print(dataset["train"][i]["text"],"\n")
    print(dataset["train"][i]["label"],"\n")
    print(dataset["train"][i]["label_text"],"\n")
    print("=="*60)

Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\band of ultra-cynics, are seeing green again.

2

Business

========================================================================================================================
Carlyle Looks Toward Commercial Aerospace (Reuters) Reuters - Private investment firm Carlyle Group,\which has a reputation for making well-timed and occasionally\controversial plays in the defense industry, has quietly placed\its bets on another part of the market.

2

Business

========================================================================================================================
Oil and Economy Cloud Stocks' Outlook (Reuters) Reuters - Soaring crude prices plus worries\about the economy and the outlook for earnings are expected to\hang over the stock market next week during the depth of the\summer doldrums.

2

Business

========================================================================================================================
Iraq Halts Oil Exports from Main Southern Pipeline (Reuters) Reuters - Authorities have halted oil export\flows from the main pipeline in southern Iraq after\intelligence showed a rebel militia could strike\infrastructure, an oil official said on Saturday.

2

Business

========================================================================================================================
Oil prices soar to all-time record, posing new menace to US economy (AFP) AFP - Tearaway world oil prices, toppling records and straining wallets, present a new economic menace barely three months before the US presidential elections.

2

Business

========================================================================================================================

In [16]:
df_train=pd.DataFrame(dataset["train"])
display(df_train)

                                                     text  label label_text
0       Wall St. Bears Claw Back Into the Black (Reute...      2   Business
1       Carlyle Looks Toward Commercial Aerospace (Reu...      2   Business
2       Oil and Economy Cloud Stocks' Outlook (Reuters...      2   Business
3       Iraq Halts Oil Exports from Main Southern Pipe...      2   Business
4       Oil prices soar to all-time record, posing new...      2   Business
...                                                   ...    ...        ...
119995  Pakistan's Musharraf Says Won't Quit as Army C...      0      World
119996  Renteria signing a top-shelf deal Red Sox gene...      1     Sports
119997  Saban not going to Dolphins yet The Miami Dolp...      1     Sports
119998  Today's NFL games PITTSBURGH at NY GIANTS Time...      1     Sports
119999  Nets get Carter from Raptors INDIANAPOLIS -- A...      1     Sports

[120000 rows x 3 columns]

In [15]:
df_test=pd.DataFrame(dataset["test"])
display(df_test)

                                                   text  label label_text
0     Fears for T N pension after talks Unions repre...      2   Business
1     The Race is On: Second Private Team Sets Launc...      3   Sci/Tech
2     Ky. Company Wins Grant to Study Peptides (AP) ...      3   Sci/Tech
3     Prediction Unit Helps Forecast Wildfires (AP) ...      3   Sci/Tech
4     Calif. Aims to Limit Farm-Related Smog (AP) AP...      3   Sci/Tech
...                                                 ...    ...        ...
7595  Around the world Ukrainian presidential candid...      0      World
7596  Void is filled with Clement With the supply of...      1     Sports
7597  Martinez leaves bitter Like Roger Clemens did ...      1     Sports
7598  5 of arthritis patients in Singapore take Bext...      2   Business
7599  EBay gets into rentals EBay plans to buy the a...      2   Business

[7600 rows x 3 columns]