In [18]:
import pandas as pd
df_train= pd.read_csv("./data/raw/df_train.csv")
df_test=pd.read_csv("./data/raw/df_test.csv")

In [19]:
import pandas as pd
import re

def normalize_text(text):
    text = text.lower()  
    text = re.sub(r'\s+', ' ', text)  
    return text.strip()


df_train['text'] = df_train['text'].apply(normalize_text)

df_test['text'] = df_test['text'].apply(normalize_text)

In [20]:
print("Nombre de doublons dans df_train :", df_train.duplicated().sum())
print("Nombre de doublons dans df_test :", df_test.duplicated().sum())

df_train = df_train.drop_duplicates()
df_test = df_test.drop_duplicates()

Nombre de doublons dans df_train : 129
Nombre de doublons dans df_test : 0

In [21]:
!pip install  nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.11/site-packages (3.9.2)
Requirement already satisfied: click in /usr/local/lib/python3.11/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/site-packages (from nltk) (4.67.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [22]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.data.path.append('/root/nltk_data')

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered_tokens = [w for w in tokens if w.lower() not in stop_words]
    return " ".join(filtered_tokens)

df_train['text_clean'] = df_train['text'].apply(remove_stopwords)
df_test['text_clean']  = df_test['text'].apply(remove_stopwords)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [23]:
def remove_punctuation(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)  
    text = re.sub(r'\s+', ' ', text)  
    return text.strip()

df_train['text_clean'] = df_train['text'].apply(remove_punctuation)
df_test['text_clean'] = df_test['text'].apply(remove_punctuation)

In [24]:
df_train.to_csv('./data/processed/df_train_preprocessed.csv',index=False)
display(df_train)

,text,label,label_text,text_clean
0,wall st. bears claw back into the black (reute...,2,Business,wall st bears claw back into the black reuters...
1,carlyle looks toward commercial aerospace (reu...,2,Business,carlyle looks toward commercial aerospace reut...
2,oil and economy cloud stocks' outlook (reuters...,2,Business,oil and economy cloud stocks outlook reuters r...
3,iraq halts oil exports from main southern pipe...,2,Business,iraq halts oil exports from main southern pipe...
4,"oil prices soar to all-time record, posing new...",2,Business,oil prices soar to all time record posing new ...
...,...,...,...,...
119995,pakistan's musharraf says won't quit as army c...,0,World,pakistan s musharraf says won t quit as army c...
119996,renteria signing a top-shelf deal red sox gene...,1,Sports,renteria signing a top shelf deal red sox gene...
119997,saban not going to dolphins yet the miami dolp...,1,Sports,saban not going to dolphins yet the miami dolp...
119998,today's nfl games pittsburgh at ny giants time...,1,Sports,today s nfl games pittsburgh at ny giants time...
119999,nets get carter from raptors indianapolis -- a...,1,Sports,nets get carter from raptors indianapolis all ...

In [25]:
df_test.to_csv('./data/processed/df_test_preprocessed.csv',index=False)
display(df_test)

,text,label,label_text,text_clean
0,fears for t n pension after talks unions repre...,2,Business,fears for t n pension after talks unions repre...
1,the race is on: second private team sets launc...,3,Sci/Tech,the race is on second private team sets launch...
2,ky. company wins grant to study peptides (ap) ...,3,Sci/Tech,ky company wins grant to study peptides ap ap ...
3,prediction unit helps forecast wildfires (ap) ...,3,Sci/Tech,prediction unit helps forecast wildfires ap ap...
4,calif. aims to limit farm-related smog (ap) ap...,3,Sci/Tech,calif aims to limit farm related smog ap ap so...
...,...,...,...,...
7595,around the world ukrainian presidential candid...,0,World,around the world ukrainian presidential candid...
7596,void is filled with clement with the supply of...,1,Sports,void is filled with clement with the supply of...
7597,martinez leaves bitter like roger clemens did ...,1,Sports,martinez leaves bitter like roger clemens did ...
7598,5 of arthritis patients in singapore take bext...,2,Business,5 of arthritis patients in singapore take bext...
7599,ebay gets into rentals ebay plans to buy the a...,2,Business,ebay gets into rentals ebay plans to buy the a...